package ai.koog.prompt.executor.clients.openai.realtime

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonObject

// ===== Session Configuration =====

/**
 * Configuration sent with [RealtimeSessionUpdateEvent] to configure the Realtime API session.
 */
@Serializable
internal data class RealtimeSessionConfig(
    /** Supported output modalities. Use ["text"] for text-only. */
    val modalities: List<String>? = null,
    /** Default system instructions for the session. */
    val instructions: String? = null,
    /** Voice for audio output (e.g. "alloy", "echo", "shimmer"). Unused in text-only mode. */
    val voice: String? = null,
    /** Available function tools for this session. */
    val tools: List<RealtimeFunctionTool>? = null,
    /** Tool choice strategy: "auto", "none", or "required". */
    @SerialName("tool_choice")
    val toolChoice: JsonElement? = null,
    /** Sampling temperature (0.6–1.2 recommended). */
    val temperature: Double? = null,
    /** Maximum output tokens per response, or "inf" for unlimited. */
    @SerialName("max_response_output_tokens")
    val maxResponseOutputTokens: JsonElement? = null,
    /** Turn detection configuration. Set to null (JSON null) to disable server VAD. */
    @SerialName("turn_detection")
    val turnDetection: JsonElement? = null,
)

/**
 * A function tool definition sent as part of session configuration.
 */
@Serializable
internal data class RealtimeFunctionTool(
    val type: String = "function",
    val name: String,
    val description: String? = null,
    val parameters: JsonObject? = null,
)

// ===== Conversation Items =====

/**
 * A conversation item that can be added via [RealtimeConversationItemCreateEvent].
 * Sealed class — subclasses represent the different item types.
 */
@Serializable
internal sealed class RealtimeItem {
    abstract val id: String?
    abstract val status: String?
}

/** A text/audio message item (user, assistant, or system role). */
@Serializable
@SerialName("message")
internal data class RealtimeMessageItem(
    override val id: String? = null,
    val role: String,
    val content: List<RealtimeContentPart>,
    override val status: String? = null,
) : RealtimeItem()

/** A function call item (generated by the model). */
@Serializable
@SerialName("function_call")
internal data class RealtimeFunctionCallItem(
    override val id: String? = null,
    val name: String,
    val arguments: String,
    @SerialName("call_id")
    val callId: String,
    override val status: String? = null,
) : RealtimeItem()

/** The output (result) of a previously requested function call. */
@Serializable
@SerialName("function_call_output")
internal data class RealtimeFunctionCallOutputItem(
    override val id: String? = null,
    @SerialName("call_id")
    val callId: String,
    val output: String,
    override val status: String? = null,
) : RealtimeItem()

/**
 * A reasoning item produced by a reasoning-capable model.
 * Pass this back in subsequent turns using [encryptedContent] to preserve multi-turn context.
 */
@Serializable
@SerialName("reasoning")
internal data class RealtimeReasoningItem(
    override val id: String? = null,
    /** Encrypted representation of the reasoning tokens — required for stateless multi-turn conversations. */
    @SerialName("encrypted_content")
    val encryptedContent: String? = null,
    /** Optional summary parts produced alongside the reasoning. */
    val summary: List<RealtimeReasoningSummary>? = null,
    override val status: String? = null,
) : RealtimeItem()

/** A single summary-text part inside a [RealtimeReasoningItem]. */
@Serializable
internal data class RealtimeReasoningSummary(
    val type: String = "summary_text",
    val text: String,
)

// ===== Content Parts =====

/** A content part within a conversation item. */
@Serializable
internal sealed class RealtimeContentPart

/** Plain text sent by the user (role=user). */
@Serializable
@SerialName("input_text")
internal data class RealtimeInputTextContent(val text: String) : RealtimeContentPart()

/** Plain text produced by the assistant (role=assistant). */
@Serializable
@SerialName("text")
internal data class RealtimeTextContent(val text: String) : RealtimeContentPart()

// ===== Client Events =====

/**
 * Events that the client sends to the Realtime API over the WebSocket.
 * The `type` discriminator field is emitted automatically by kotlinx.serialization.
 */
@Serializable
internal sealed class RealtimeClientEvent

/** Configures or reconfigures the active session. */
@Serializable
@SerialName("session.update")
internal data class RealtimeSessionUpdateEvent(
    val session: RealtimeSessionConfig,
    @SerialName("event_id")
    val eventId: String? = null,
) : RealtimeClientEvent()

/** Appends a new item to the conversation. */
@Serializable
@SerialName("conversation.item.create")
internal data class RealtimeConversationItemCreateEvent(
    val item: RealtimeItem,
    @SerialName("previous_item_id")
    val previousItemId: String? = null,
    @SerialName("event_id")
    val eventId: String? = null,
) : RealtimeClientEvent()

/** Triggers the model to generate a response for the current conversation. */
@Serializable
@SerialName("response.create")
internal data class RealtimeResponseCreateEvent(
    val response: RealtimeResponseConfig? = null,
    @SerialName("event_id")
    val eventId: String? = null,
) : RealtimeClientEvent()

/** Per-response configuration overrides for [RealtimeResponseCreateEvent]. */
@Serializable
internal data class RealtimeResponseConfig(
    val modalities: List<String>? = null,
    val tools: List<RealtimeFunctionTool>? = null,
    @SerialName("tool_choice")
    val toolChoice: JsonElement? = null,
    val temperature: Double? = null,
)

// ===== Server-side data types =====

/**
 * Metadata about a newly added output item, received in [RealtimeResponseOutputItemAddedEvent].
 * Used to extract the function name before argument streaming begins.
 */
@Serializable
internal data class RealtimeOutputItemInfo(
    val id: String? = null,
    val type: String,
    /** Function name — only present when [type] == "function_call". */
    val name: String? = null,
    /** Call identifier linking the function call to its output. */
    @SerialName("call_id")
    val callId: String? = null,
    val status: String? = null,
)

/**
 * Full item payload carried by `response.output_item.done`.
 * Used to construct [ai.koog.prompt.streaming.StreamFrame.ReasoningComplete] for reasoning items.
 */
@Serializable
internal data class RealtimeOutputItemDonePayload(
    val id: String? = null,
    val type: String,
    /** Encrypted reasoning tokens — only present for `type == "reasoning"` and when requested. */
    @SerialName("encrypted_content")
    val encryptedContent: String? = null,
    /** Summary parts — only present for `type == "reasoning"`. */
    val summary: List<RealtimeReasoningSummary>? = null,
)

/** Response result payload inside [RealtimeResponseDoneEvent]. */
@Serializable
internal data class RealtimeResponseResult(
    val id: String,
    val status: String,
    val usage: RealtimeUsage? = null,
)

/** Token usage reported at the end of a response. */
@Serializable
internal data class RealtimeUsage(
    @SerialName("total_tokens")
    val totalTokens: Int? = null,
    @SerialName("input_tokens")
    val inputTokens: Int? = null,
    @SerialName("output_tokens")
    val outputTokens: Int? = null,
)

/** Error payload inside [RealtimeErrorEvent]. */
@Serializable
internal data class RealtimeError(
    val type: String? = null,
    val code: String? = null,
    val message: String,
    val param: String? = null,
)
